const characters = [
  {
    id: 1,
    charName: "Mithandir",
    race: "Elfo",
    charClass: "Mago",
    level: 10,
    gold: 4250,
    playerName: "Daniel",
    isActive: true,
    image: "../img/mithrandir.jpg",
  },
  {
    id: 2,
    charName: "Heos",
    race: "Humano",
    charClass: "Paladín",
    level: 12,
    gold: 7450,
    playerName: "Carlos",
    isActive: true,
    image: "../img/heos.jpg",
  },
  {
    id: 3,
    charName: "Melkor",
    race: "Orco",
    charClass: "Mercenario",
    level: 8,
    gold: 1480,
    playerName: "Pablo",
    isActive: false,
    image: "../img/melkor.jpg",
  },
  {
    id: 4,
    charName: "Yorim",
    race: "Enano",
    charClass: "Guerrero",
    level: 4,
    gold: 300,
    playerName: "Javier",
    isActive: true,
    image: "../img/yorim.jpg",
  },
  {
    id: 5,
    charName: "Sanga",
    race: "Elfo Oscuro",
    charClass: "Ilusionista",
    level: 12,
    gold: 3500,
    playerName: "Juan",
    isActive: true,
    image: "../img/sanga.jpg",
  },
  {
    id: 6,
    charName: "Valamarth",
    race: "Humano",
    charClass: "Asesino",
    level: 8,
    gold: 1200,
    playerName: "Pablo",
    isActive: true,
    image: "../img/valamarth.jpg",
  },
  {
    id: 7,
    charName: "Rauko",
    race: "Orco",
    charClass: "Duelista",
    level: 3,
    gold: 800,
    playerName: "Javier",
    isActive: false,
    image: "../img/rauko.jpg",
  },
  {
    id: 8,
    charName: "Ulmi",
    race: "Goblin",
    charClass: "Ladron",
    level: 15,
    gold: 9200,
    playerName: "Daniel",
    isActive: true,
    image: "../img/ulmi.jpg",
  },
  {
    id: 9,
    charName: "Shinji",
    race: "Elfo",
    charClass: "Arquero",
    level: 11,
    gold: 7300,
    playerName: "Carlos",
    isActive: false,
    image: "../img/shinji.jpg",
  },
  {
    id: 10,
    charName: "Ardanal",
    race: "Humano",
    charClass: "Sanador",
    level: 20,
    gold: 7800,
    playerName: "Andrea",
    isActive: true,
    image: "../img/ardanal.jpg",
  },
];
